# Generated by Django 5.2.2 on 2025-06-06 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('carnes', 'Carnes'), ('verduras', 'Verduras')], max_length=20)),
                ('imagem', models.ImageField(blank=True, upload_to='produtos/')),
                ('codigo', models.CharField(blank=True, max_length=100)),
                ('formato', models.CharField(choices=[('code128', 'Code-128')], max_length=20)),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to='barcodes/')),
            ],
        ),
    ]
