# Generated by Django 5.2.2 on 2025-06-06 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='formato',
            field=models.CharField(choices=[('code128', 'Code 128'), ('code39', 'Code 39'), ('ean13', 'EAN-13'), ('ean8', 'EAN-8'), ('upca', 'UPC-A'), ('jan', 'JAN'), ('isbn13', 'ISBN-13'), ('isbn10', 'ISBN-10'), ('issn', 'ISSN'), ('pzn', 'PZN'), ('ean14', 'EAN-14'), ('gs1_128', 'GS1-128'), ('itf', 'ITF'), ('codabar', 'Codabar')], max_length=20),
        ),
    ]
